name         'myoung34-marklogic'
version '0.0.4'
source       'http://github.com/myoung34/puppet-marklogic'
author       'Marcus Young'
license      'GPLv3+'
summary      'Puppet MarkLogic management module'
description  'This module can be used for basic MarkLogic Management'
project_page 'http://github.com/myoung34/puppet-marklogic'

dependency 'puppetlabs/stdlib',   '>= 0.1.6'
dependency 'puppetlabs/firewall', '>= 0.3.0'
